// Copyright (C) Fabien Poupineau. All Rights Reserved.

#pragma once

// UE5
#include "NativeGameplayTags.h"


namespace ArcUITags
{
	ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArcUIRoot);
	ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ViewRoot);
	ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ContextRoot);

	namespace Layer
	{
		ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(LayerRoot);

		namespace HUD
		{
			ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Low);
			ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(High);
		}

		ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Menu);
		ARCUIFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modal);
	}
}
